### ISSUE TITLE
macOS pristine run-python-bindings fails

### ISSUE THREAD

**Issue by TinoDidriksen** [divvun/libdivvun#10]
Probably important part `Library not loaded: /usr/local/lib/libdivvun.0.dylib` - test seems to expect globally installed library, but it hasn't been installed yet.

````
FAIL: ./run-python-bindings
===========================

running install
running build
running build_py
running build_ext
running install_lib
creating /tmp/libdivvun/test/checker/python-build
copying build/lib.macosx-10.13-x86_64-3.6/_libdivvun.cpython-3.6m.so -> /tmp/libdivvun/test/checker/python-build
copying build/lib.macosx-10.13-x86_64-3.6/_libdivvun.cpython-36m-darwin.so -> /tmp/libdivvun/test/checker/python-build
copying build/lib.macosx-10.13-x86_64-3.6/libdivvun.py -> /tmp/libdivvun/test/checker/python-build
byte-compiling /tmp/libdivvun/test/checker/python-build/libdivvun.py to libdivvun.cpython-36.pyc
running install_egg_info
Writing /tmp/libdivvun/test/checker/python-build/python_divvun_gramcheck-0.2.0-py3.6.egg-info
Traceback (most recent call last):
  File "/tmp/libdivvun/test/checker/python-build/libdivvun.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/tmp/libdivvun/test/checker/python-build/_libdivvun.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/lib/libdivvun.0.dylib
  Referenced from: /tmp/libdivvun/test/checker/python-build/_libdivvun.cpython-36m-darwin.so
  Reason: image not found
````

````
$ otool -L /tmp/libdivvun/test/checker/python-build/_libdivvun.cpython-36m-darwin.so
/tmp/libdivvun/test/checker/python-build/_libdivvun.cpython-36m-darwin.so:
        /usr/local/lib/libdivvun.0.dylib (compatibility version 1.0.0, current version 1.0.0)
````

Might need fiddling with `install_name_tool` or `DYLD_LIBRARY_PATH`.

**Comment by TinoDidriksen** [comment]
Fixed in https://github.com/divvun/libdivvun/commit/2813470f72bcbcc54e77334dcd12e810796830d1
